### ISSUE TITLE
[BUG] HTTPError: Not Found

### ISSUE THREAD

**Issue by scalen** [tianhaoz95/approveman#530]
**Describe the bug**
When creating a PR, the Approveman check failed (not neutral, but failed) with the following error:

```
HttpError: Not Found
at /app/node_modules/@octokit/request/dist-node/index.js:86:21
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async sendRequestWithRetries (/app/node_modules/@octokit/auth-app/dist-node/index.js:454:12)
at async Job.doExecute (/app/node_modules/bottleneck/light.js:405:18)
```

**To Reproduce**
1. Add Approveman to your repo.
2. Configure it with limited scope for auto-approved changes (this happened  with an allow-listed user, but it isn't clear if that is related).
3. Create a PR (with an allowed user) containing changes outside of the defined scope.
4. See error.

**Expected behavior**
The Approveman check should not succeed, but should complete with a neutral status.

**Screenshots**
![image](https://user-images.githubusercontent.com/3024226/131682777-5cbab4dd-9e44-4ecb-909c-4eaafb4fc1db.png)

**Comment by tianhaoz95** [comment]
Hi @scalen , thanks for the ping! Yes, the idea is to return a neutral check and let developer decide how to proceed. It looks like an API endpoint is not liking it. I will take a look and resolve this in a few hours.

**Comment by scalen** [comment]
Looks to be fixed now, thanks 🙂
