### ISSUE TITLE
approveman does not support deviating appname

### ISSUE THREAD

**Issue by epDHowwD** [tianhaoz95/approveman#64]
I built and installed this app on a GitHub enterprise server and prefixed the app name with our project name (as gh enterprise does not scope apps). So then the name of the app (and hence the reviewing "user") was not `approveman[bot]` as hard coded in the code. Thus, the app was not able to dismiss its own review.

**Comment by tianhaoz95** [comment]
@epDHowwD Ah that's a problem. I wasn't thinking too much about the enterprise initially. Can you post a sample how the naming scheme work in enterprise so that I can fix that in the code.

**Comment by tianhaoz95** [comment]
So far I think there are 2 possible solutions:
1. allow the DIY user to override the app name with APP_NAME_OVERRIDE while building and deployment.
2. fetch the application name with the self auth in GitHub API.

Also, I do thing they can co-exist.

**Comment by tianhaoz95** [comment]
Yea I think both mechanisms should exist since GitHub enterprise is not listed in marketplace subscription, there is really not way for the app to know what the name is from GitHub. Please let me know if you have other good ideas @epDHowwD

**Comment by epDHowwD** [comment]
You may try to use the [authenticated app endpoint](https://developer.github.com/v3/apps/#get-the-authenticated-app). It returns the configured name, id, avatar, and even the html_url and external_url, which might be interesting for status posts. 
I don't now much about probot app development, so it is just a guess. 

As we are building the app from source, a central modifiable variable would already do the trick. Also ENV during build-time or runtime would work.

As you asked for examples for our naming schemes, we prefix the apps usually with an organization name separated with `-`. However, I do not recommend to stick to this in your app.

**Comment by tianhaoz95** [comment]
@epDHowwD  Yes I think the get app API is a good next thing to explore. At the same time , the app name can now be configured with `APP_ACTOR_NAME_OVERRIDE ` either in environment or .env which is added in #69

**Comment by epDHowwD** [comment]
![image](https://user-images.githubusercontent.com/37585964/93048959-5addcc80-f660-11ea-9b4a-37634bddad4a.png)
Works as expected and out of the box. Thank you very much @tianhaoz95 !
